baseurl: /tvimageplus/
url: https://alanpich.github.io/tvimageplus
author: Alan Pich


markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis","fenced_code_blocks","tables","autolink","strikethrough","superscript","with_toc_data"]

redcloth:
  hard_breaks: false